formatter: markdown table
header-from: readme_header.md

sections:
  show-all: true
  #show:
  #  - header
  #  - inputs
  #  - outputs
  #  - providers
  #  - requirements


sort:
  enabled: true
  by: required

settings:
  color: true
  escape: true
  indent: 2
  required: true
  sensitive: true